# -*- coding: utf-8 -*-
"""PRODIGY_CS_05

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19LsTwbWZIKceyRFJLD5EKfxXyU2Cmd5K
"""

pip install scapy

from scapy.all import sniff
from scapy.layers.inet import IP, TCP, UDP

def packet_callback(packet):
    if IP in packet:
        ip_layer = packet[IP]
        print(f"Source IP: {ip_layer.src}")
        print(f"Destination IP: {ip_layer.dst}")

        if TCP in packet:
            tcp_layer = packet[TCP]
            print(f"Protocol: TCP")
            print(f"Source Port: {tcp_layer.sport}")
            print(f"Destination Port: {tcp_layer.dport}")
            if len(tcp_layer.payload) > 0:
                print(f"Payload: {tcp_layer.payload}")

        elif UDP in packet:
            udp_layer = packet[UDP]
            print(f"Protocol: UDP")
            print(f"Source Port: {udp_layer.sport}")
            print(f"Destination Port: {udp_layer.dport}")
            if len(udp_layer.payload) > 0:
                print(f"Payload: {udp_layer.payload}")

        print("-" * 50)


print("Starting packet sniffer...")
sniff(prn=packet_callback, store=0)